name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.ref == github.event.repository.default_branch
    steps:
      - name: ref
        run: echo ${{ github.ref }}
      - name: branch
        run: echo ${{ github.event.repository.default_branch }}