name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: ref
        run: echo ${{ github.ref_name }}
      - name: branch
        run: echo ${{ github.event.repository.default_branch }}